[project]
name = "experiments-analysis"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "matplotlib>=3.10.3",
    "numpy>=2.2.5",
    "polars>=1.29.0",
    "scipy>=1.15.3",
    "sqlalchemy>=2.0.41",
]

[dependency-groups]
dev = [
    "marimo>=0.13.10",
]
